### PR TITLE
Feat[Renderer]: Create a dedicated framebuffer for the virgl renderer

### PR DESCRIPTION
**Pull request by Vera-Firefly**

### CODE REVIEW

**Comment by SolDev69** [comment]
Will this fix virgl on new mesa?

**Comment by Vera-Firefly** [comment]
> Will this fix virgl on new mesa?

Can't

**Comment by Vera-Firefly** [comment]
It provides a frame buffer for the virgl renderer

**Comment by Vera-Firefly** [comment]
It has nothing to do with Mesa

**Comment by Vera-Firefly** [comment]
The malloc was originally used, but it was considered to be uninitialized, so it was replaced by calloc

**Comment by Vera-Firefly** [comment]
> The malloc was originally used, but it was considered to be uninitialized, so it was replaced by calloc

This is what I accidentally deleted when I ~~updated~~ refactord it, and now I'm adding it back.

**Comment by SolDev69** [comment]
Alright

**Pull request merged**
