### PR TITLE
Create a dedicated buffter for virgl

### PR DESCRIPTION
**Pull request by Vera-Firefly**

### CODE REVIEW

**Comment by WesleyVanNeck** [comment]
Virgl doesnt show up

**Comment by WesleyVanNeck** [comment]
Screenshot_20240113-195028_PojavLauncher (Minecraft_ Java Edition voor Android)

**Comment by SolDev69** [comment]
> Virgl doesnt show up

have to add that back in strings.xml and headings_array.xml

**Comment by Vera-Firefly** [comment]
Sorry, I didn't look carefully

**Comment by Vera-Firefly** [comment]
Okay, that's already added

**Comment by Vera-Firefly** [comment]
Note that I did not provide the libOSMesa_81.so, you need to add it yourself.

**Comment by Vera-Firefly** [comment]
And vtest

**Comment by Vera-Firefly** [comment]
If you just want to test the usability of the code, you can upload and compile the two files from me first

**Comment by Vera-Firefly** [comment]
> If you just want to test the usability of the code, you can upload and compile the two files from me first

I can make sure it's working

**Comment by Vera-Firefly** [comment]
If there is anything else you need to communicate, you can send me an email,you know, I'm from China, and sometimes it's difficult to access discord,1964762970@qq.com and verafirefly0515@outlook.com  , these are both my email addresses, and you can send an email to either one.

**Comment by SolDev69** [comment]
I'll probably be using mesa 22.0.5 for virgl btw, it should work with old vtest tho

**Comment by Vera-Firefly** [comment]
> I'll probably be using mesa 22.0.5 for virgl btw, it should work with old vtest tho

It can all be used

**Pull request merged**
